fixtures:
  symlinks:
    dbus: "#{source_dir}"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "7.1.0"
  repositories:
    facts: "https://github.com/puppetlabs/puppetlabs-facts.git"
    provision: "https://github.com/puppetlabs/provision.git"
    puppet_agent: "https://github.com/puppetlabs/puppetlabs-puppet_agent.git"
